server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test  # test ??? ??? ??? ??? ???? ???.
    username: sa # username? password? ??? ??? ??
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # ??????? ??? ? ??????? ????? ?? ??? ??
    properties:
      hibernate:
        format_sql: true # ???? query? ???
        show_sql: true

logging.level:
  org.hibernate.SQL: debug